kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage-redis
  namespace: db-system
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain