apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  namespace: db-system
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage-redis
  local:
    path: "/opt/redis"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key:  kubernetes.io/arch
          operator: In
          values:
          - amd64